version: "3.0"
networks:
    gcp_network:
      name: "peter"
      driver: bridge
      external: false

services:
  prod.crm.fe.customer:
    labels:
      svc: "prod.crm.fe.customer"
    container_name: prod.crm.fe.customer
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - gcp_network